### ISSUE TITLE
Subtract window area from wall area

### ISSUE THREAD

**Issue by PhilPJL** [TrystanLea/heatlossjs#5]
It would be useful if there was an way to subtract window from wall area

![image](https://github.com/TrystanLea/heatlossjs/assets/271656/7b441efb-8d10-47d1-9d79-ce5cf69a6ed4)
The windows are all in the west facing wall.  As per the MCS calculator it would useful if the calculation adjusted the effective wall area by subtracting the window area.

**Comment by TrystanLea** [comment]
Hello, this is implemented , though not obvious, see the example heat loss
when you first load the tool, windows are subtracted from earlier element
IDs

**Comment by PhilPJL** [comment]
I don't see it working at the moment.  I will investigate further tomorrow.

**Comment by PhilPJL** [comment]
If I create a new project and add these two elements 

![image](https://github.com/TrystanLea/heatlossjs/assets/271656/44ee8e51-ddb3-413a-8520-838415551f39)

The total is just the sum of the two elements.  Am I missing something?

**Comment by TrystanLea** [comment]
I've added a title to highlight the subtract column, called 'Sub':

![image](https://github.com/TrystanLea/heatlossjs/assets/503186/3c0d260f-4500-417d-a642-033c21757e18)
